### ISSUE TITLE
Enhancement: spectator link

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#1192] opened 2020-08-20 13:37 UTC
Upon game creation, in addition to making each link for each player. Create another link for spectators to watch the game. Spectators cannot see cards in any player's hand but can see everything else. Spectators cannot take any action.

**Comment by funkybaboon** [comment] 2020-10-24 08:16
This is also a great enhancement to watch your opponents on a second screen. Spectators should be able to see played hands.

**Comment by kevinb9n** [comment] 2020-12-24 06:38
Idea: every player has a spectate-me link somewhere on their game page which they can send to anyone at any time, allowing the link recipient to spectate the game and see that player's cards only.

**Comment by bafolts** [comment] 2021-03-24 14:16
This is duplicate of #3015

**Comment by kberg** [comment] 2021-08-28 02:52
Wrong working PR. Moving to #3015

**Closed by kberg** 2021-08-28 02:52 UTC
Labels: enhancement
