### ISSUE TITLE
Bug? Aridor Colony breaks End-of-Turn Calculations

### ISSUE THREAD

**Issue by Chosrau** [bafolts/terraforming-mars#1142] opened 2020-08-12 16:43 UTC
In game https://terraforming-mars.herokuapp.com/player?id=44467552d86e

Upon all players passing, game wouldn't properly proceed to next generation. Production Phase did happen. Turmoil Phase did not happen. All Colony tracks before the Aridor Colony would advanace in track, but the Aridor Colony and everyone after it the track would stay the same. Card Phase did not happen.

Game then resumed but stayed in Generation 1, therefore players could take their corporation first actions again(for example Aridor could place another colony, which also showed the same behaviour)

**Comment by Lynesth** [comment] 2020-12-17 04:46
Could not reproduce and was not reported again, closing.
Feel free to reopen if it happens again.

**Closed by Lynesth** 2020-12-17 04:46 UTC
Labels: question
