### ISSUE TITLE
Atmoscoop bug

### ISSUE THREAD

**Issue by KrivisLTU** [bafolts/terraforming-mars#1172] opened 2020-08-16 16:26 UTC
During a game today, when I played Atmoscoop, I wasn't prompted the selection between temperature and Venus, and instead temperature was raised instantly. Don't know if it is easily recreatable, as the selection button might have just been bugged and triggered twice.

**Comment by duckmammal** [comment] 2020-08-16 18:51
I've had this happen a number of times too. I came to question my sanity, because it's not reproducible for me.

I kept wondering if I somehow double-clicked the confirm button, and then it took the second confirmation and applied it to the next screen.

**Comment by nwai90** [comment] 2020-08-17 00:16
This happens when one of the parameters is maxed out. Atmoscoop will automatically raise the other parameter two steps.

**Comment by duckmammal** [comment] 2020-08-17 06:12
But it was not the case that one of the parameters was maxed. I would not be interested in raising a maxed param.

**Comment by KrivisLTU** [comment] 2020-08-17 06:31
Same with me, Venus was at 6%, and temp was at around ~-10°C. But once again, maybe it just lagged and double clicked for us

**Comment by vincentneko** [comment] 2020-08-17 06:38
Just checked the code.
The `play()` method uses `return game.increaseTemperature(player,2);` or `return game.increaseVenusScaleLevel(player,2);`
It should do 
```
game.increaseTemperature(player,2);
return undefined;
```

or 
```
game.increaseVenusScaleLevel(player,2);
return undefined;
```
As it is difficult to reproduce I'm not sure if this will solve the issue, but worth to try imho.

**Comment by vincentneko** [comment] 2020-08-17 12:05
If someone knows how to reproduce the bug, please let us know.

**Comment by duckmammal** [comment] 2020-08-18 13:22
It happened in this Solo game in Gen 10. I can't figure out the circumstances for why it happened though. Maybe because it was going to get me an ocean if I took it as 2 Temperature increases?

**Comment by vincentneko** [comment] 2020-08-24 07:06
Should be fixed now

**Closed by vincentneko** 2020-08-24 07:06 UTC
