### ISSUE TITLE
Option to include Prelude project cards, without using preludes.

### ISSUE THREAD

**Issue by ricardoflmagalhaes** [bafolts/terraforming-mars#2199] opened 2020-12-28 15:21 UTC

**Comment by kberg** [comment] 2020-12-28 15:26
What does that mean?

**Comment by ricardoflmagalhaes** [comment] 2020-12-28 15:35
> I don't understand what that means, can you expand on it?

When I play my physical version of TRM, I always include Prelude project cards, even when not using preludes, since they don't require other components from expansion.
https://ssimeonoff.github.io/cards-list#P36#P37#P38#P39#P40#P41#P42

**Comment by bafolts** [comment] 2020-12-28 15:48
This is the opposite ask of #1440 where some cards want to be excluded. In this case some cards want to be included. We may be better off having all the cards listed out and then using the same interface we use when including or excluding corporation cards.

**Comment by kberg** [comment] 2020-12-28 15:58
Oh I get it now: including the *project cards* from Prelude. Yeah, I see.

**Comment by kevinb9n** [comment] 2020-12-28 17:25
#1445 is the more general request.

**Comment by Lynesth** [comment] 2021-01-27 12:02
Duplicate of #1445.

**Closed by Lynesth** 2021-01-27 12:02 UTC
