### ISSUE TITLE
worldGovernmentTerraforming is not a function

### ISSUE THREAD

**Issue by MartinAtHome** [bafolts/terraforming-mars#2126] opened 2020-12-15 16:43 UTC
A game on my private Heroku instance received "Unexpected Server Response". I updated to the latest from git to see if a bug had been fixed and this was in my log upon restart:

`2020-12-15T15:55:02.836067+00:00 app[web.1]: unable to load game 1b6dc9ea0d3e TypeError: this.first.worldGovernmentTerraforming is not a function`

I have a postgres db attached. The game had completed Prelude and Turn 1...players were choosing which cards to keep from the first draft.

**Comment by MartinAtHome** [comment] 2020-12-16 00:48
Confirmed with new game started after latest pull:
`heroku logs | Select-String -Pattern f1b901e54513                        
2020-12-15T21:50:02.219065+00:00 app[web.1]: unable to load game f1b901e54513 TypeError:
this.first.worldGovernmentTerraforming is not a function
2020-12-15T22:26:03.484700+00:00 app[web.1]: unable to load game f1b901e54513 TypeError:
this.first.worldGovernmentTerraforming is not a function


PS C:\Users\mburk\git\TMars\terraforming-mars> git pull origin main
From https://github.com/bafolts/terraforming-mars
 * branch              main       -> FETCH_HEAD
Already up to date.`

**Comment by kberg** [comment] 2020-12-16 00:50
Thanks, Martin.

**Comment by bafolts** [comment] 2020-12-16 00:53
This could be a bug with deserialization.

**Comment by MartinAtHome** [comment] 2020-12-16 00:55
Thanks all

**Comment by kberg** [comment] 2020-12-16 00:56
Yeah.

**Comment by bafolts** [comment] 2020-12-16 00:58
Did you mean to close this @kberg ?

**Comment by kberg** [comment] 2020-12-16 03:12
Yuck, I did but I read it as "this if fixed."

>

**Comment by bafolts** [comment] 2020-12-16 15:53
With these matters of deserializing it can be difficult to know if it is a bug. We can only try to work when deserializing data which may have been saved from previous version. If somehow a user had serialized data from many versions ago their game could be lost during an update. I will see what could have caused this and close if deemed it was due to an update from many version back.

@MartinAtHome how often do you update your private heroku? Would the game have been saved in a fairly recent version of the app?

**Comment by bafolts** [comment] 2020-12-28 15:44
Can't reproduce.

**Closed by bafolts** 2020-12-28 15:44 UTC
