### ISSUE TITLE
Bug: Virus should be able to remove one animal

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#2014] opened 2020-12-05 18:35 UTC
In a game with @nwai90 and @ssimeonoff, we found that Virus could NOT be used on small animals which has 1 animal. Perhaps the card code is too restrictive and only tries to remove 2.

**Comment by vsrisuknimit** [comment] 2020-12-05 18:35
I had Asteroid Deflection System. Just in case there is a bug there that protects animals instead.

**Comment by bafolts** [comment] 2020-12-05 21:16
I can't spot this issue in source. Any idea what other cards were played?

**Comment by Lynesth** [comment] 2020-12-06 16:09
Can reproduce either. Are you sure it wasn't Pets ?

**Comment by nwai90** [comment] 2020-12-07 00:39
It was Small Animals. Simon had only Asteroid Deflection Systems played. Strangely I cannot reproduce the issue either, think we can close this one.

**Closed** 2020-12-07 00:41 UTC
Labels: bug
