### ISSUE TITLE
Card vanished from Self-Replicating Robots

### ISSUE THREAD

**Issue by kevinb9n** [bafolts/terraforming-mars#2278] opened 2021-01-05 17:20 UTC
Gorg on discord:
had a bug today, had phobos on self-replicating robots. It just dissappeared from play, inexplicably. Normally it would be listed at the very bottom. Simply removed from my hand
apologies if known bug

me on discord:
Okay I've triple checked this.  A Capital card vanished off of my SRR. (I scrolled up a bit in the log to show that it had been there)
<img width=400 src=https://user-images.githubusercontent.com/934551/103677473-353e4100-4f37-11eb-864b-be1fcbdc1d5b.png>

I think it happened when I undid placing a greenery tile. I always reload right after undo and then I noticed the thing was gone.
I went ahead and finished the generation in case something kinda reset it, but no. I guess I'll leave it in this state now. https://terraforming-mars.herokuapp.com/player?id=4dcdfac088e0

**Comment by bafolts** [comment] 2021-01-05 17:26
Leaving it in it's state is great! This is either going to be related to the serialization changes since they mention undo or the card change to use less memory. The good news here is that the `terraforming-mars.herokuapp.com` is running great! Now have to address these bugs.

**Comment by bafolts** [comment] 2021-01-08 01:59
I haven't been able to recreate this easily in a unit test. The screenshot is fairly telling though. When I serialize a player and then deserialize I see the target card.

**Comment by bafolts** [comment] 2021-01-09 02:13
I am unable to recreate and we delete old games from server after one day so I was unable to pull the JSON that was saved for this game. This screenshot could be user error. If the capital card were played it is removed from self-replicating robots. Without data in the screenshot or logs to know if the capital card were played which would have removed it from self-replicating robots I am closing this issue. Verified there wasn't some obvious issue with serialize or deserialize. Will need steps to reproduce if this is an issue. Can re-visit if we get more reports.

**Comment by kevinb9n** [comment] 2021-01-09 19:53
I'm known to make at least my share of user error. In this case though, it should be hard to imagine what would motivate a person to file a bug report about a missing Capital while a shiny Capital tile was sitting right there on the board the whole time. It just seems implausible to me - and there was a second independent report too.

So I think this will probably bite someone else (less likely to be me as I am avoiding playing SRR now!). 
If it happens again, what can we do to preserve the data?

**Comment by bafolts** [comment] 2021-01-10 16:50
We were deleting game entries after one day for single player games in a desperate measure to keep the server up a few months ago. We shouldn't need to do that anymore. We delete the data for multi player games after 10 days. Should be fine to allow for 10 days for single player games as well again. This will at least give us some time to pull the data when a bug report comes in.

**Comment by kevinb9n** [comment] 2021-01-10 23:51
Gorg
Today at 12:46 PM
a week or so ago I reported a self replicating robots bug, where the selected card disappeared from my hand
it happened again just now
fyi match ID b05f7b4988aa

**Comment by bafolts** [comment] 2021-01-10 23:54
This game is two player so we should have it for 10 days. 

http://terraforming-mars.herokuapp.com/player?id=b00b1bb7d779&noredirect

Will see if anything stands out with data available. When you finish a game I think we delete all history which isn't helpful. Should have the full game log though.

**Comment by Lynesth** [comment] 2021-01-11 03:15
I can reproduce and will submit a fix soon.

**Closed** 2021-01-11 06:49 UTC
Labels: bug
