### ISSUE TITLE
Bug? Unable to begin solo game after choosing cards

### ISSUE THREAD

**Issue by Dudurandil** [bafolts/terraforming-mars#1138] opened 2020-08-11 19:56 UTC
Hi,

I can't start this game https://terraforming-mars.herokuapp.com/player?id=8692aacac00e after choosing Corporation, Preludes and starting project cards. (All expansions) 

"Not your turn to take any actions" appears on screen.

Thanks for your help!

**Comment by chosta** [comment] 2020-08-12 06:55
Hi, you are correct. There seems to be a bug that does not let you play your turn. I'll try to find the problem. We get these now and then and until we fix all the problems my advice is to start over :)

**Comment by Dudurandil** [comment] 2020-08-12 07:49
Oh I see, I'll apply your advice :) Thanks again!

**Comment by vincentneko** [comment] 2020-08-12 08:11
Looks like a bug related with prelude, as the game should prompt prelude cards to play.
Do you remember the preludes you had chosen ?

**Comment by vincentneko** [comment] 2020-08-12 08:16
@bafolts do you have a way to get the game_id linked with player_id 8692aacac00e ?
Having the game id would enable to replay this game and investigate more.

**Comment by Dudurandil** [comment] 2020-08-12 10:47
If I remember well, I chose Huge Asteroid and Self-sufficient Settlement

**Comment by pierrehilbert** [comment] 2020-08-26 15:14
If no one reproduce the problem, I propose that we are closing this issue

**Comment by vincentneko** [comment] 2020-08-27 06:11
It may be correlated with server restart. Let's close it if it's not reproducible.

**Closed by vincentneko** 2020-08-27 06:11 UTC
Labels: bug
