### ISSUE TITLE
Permit playing an action that legally has no effect

### ISSUE THREAD

**Issue by kevinb9n** [bafolts/terraforming-mars#1474] opened 2020-10-04 19:17 UTC
thenewjuniorexecutive Today at 10:33 AM
"Taking Directed Impactors action with a resource on it and temp maxed forces you to pay for another resource. Removing a resource is a valid stall in this situation since raising maxed params is not required to complete an action.'

I believe this is correct, and I think I saw this with Aquifer Pumping as well.

**Comment by kevinb9n** [comment] 2020-10-04 19:20
Oh: the same applies to Symbiotic Fungus when you have no microbe-accepting card. Etc.

(The third exception to the no-partial-actions rule is removing resources from an opponent, I just don't know of any actions that have that as their right-hand-side.)

**Comment by vsrisuknimit** [comment] 2020-10-05 01:38
@kevinb9n Ants and Predators can remove their own and add back to themselves.

**Comment by kevinb9n** [comment] 2020-10-05 03:04
That is correct... but is it related to this issue? That describes an action that has two effects, which both actually happen.

**Comment by vsrisuknimit** [comment] 2020-10-05 11:16
@kevinb9n sorry I misunderstood your third exception. Please ignore me.

**Comment by bafolts** [comment] 2020-10-05 23:40
This change will most likely need to fix various cards as the issue is spotted. As the `canPlay` and `canAct` methods were implemented this changed. There was a mindset that if the action doesn't make sense we should not show the card as a user most likely doesn't want to play it. I agree though that we should allow any action that is legally possible even if it isn't clear why someone would want to take that action.

**Comment by nwai90** [comment] 2020-10-06 02:56
Yes, stall actions do have some value in late game. Will fix along the way as we discover them

**Comment by nwai90** [comment] 2020-10-12 06:11
Fixed and merged

**Closed by nwai90** 2020-10-12 06:11 UTC
