### ISSUE TITLE
Working on a Spanish translation

### ISSUE THREAD

**Issue by diegombeltran** [bafolts/terraforming-mars#2825] opened 2021-02-22 22:42 UTC
Hello!

A friend of mine and I are working on a Spanish (Spain) translation based on the official one. We are taking the German translation as a starting point and currently have translated 150/233 base box cards, and most of the UI strings.

If someone would like to contribute, or seek for typos, mistakes... you are all welcome.
[Here is the fork](https://github.com/diegombeltran/terraforming-mars). I have the original box in Spanish and three expansions in English so until I can borrow Spanish versions to obtain the official card descriptions, we may need some help.

Also I would like to thank all contributors who made this app possible, because it's been a really good job.

**Comment by vsrisuknimit** [comment] 2021-02-23 00:59
@diegombeltran it might be better to take the Russian or Chinese translation as the starting point. They are more completed than the German one.

Come say hi on Discord (https://discord.gg/VR8TbrD). Maybe you can find other Spanish speakers to help there.

**Comment by bafolts** [comment] 2021-02-23 02:35
¡Gracias!

**Comment by diegombeltran** [comment] 2021-02-23 07:17
> @diegombeltran it might be better to take the Russian or Chinese translation as the starting point. They are more completed than the German one.
> 
> Come say hi on Discord (https://discord.gg/VR8TbrD). Maybe you can find other Spanish speakers to help there.

We realised that, yes. Will take a look to the differences between files and update. I will join Discord this evening, thank you for your advice!

**Comment by andres-lr** [comment] 2021-02-24 12:29
> If someone would like to contribute, or seek for typos, mistakes... you are all welcome.
> [Here is the fork](https://github.com/diegombeltran/terraforming-mars). I have the original box in Spanish and three expansions in English so until I can borrow Spanish versions to obtain the official card descriptions, we may need some help.

Hello there fellow terraformer! I was on my way to translate the app too! It would be wonderful if we could work together :)

Maybe we can meet and decide how to work on this? Divide the work and that stuff. I have 3 official expansions in Spanish, so that might help getting the best translation possible, while we can discuss on the the other untranslated stuff.

**Comment by ErikVifrey** [comment] 2021-02-24 18:21
Hi everyone!
I am very excited to be contributing to the Spanish translation with @diegombeltran. We have already translated most of the base game, UI and settings strings. @andres-lr a Discord invitation has been sent!
See you guys on Discord!

**Comment by diegombeltran** [comment] 2021-03-01 22:12
Hello!

Just wanted to share that a lot of strings are already translated. I'll buy Venus Next and Colonies this week and that would be all left. Thanks to @ErikVifrey and @andres-lr who did a huge job these days.

I'd like to know if standardization of locales is in the roadmap. We found many inconsistencies such as some strings ending with a dot, whereas others aren't; the same for many words in capital letters, etc.

We also noticed that each translation groups strings differently. I know that it depends on contributors, but maybe the same set of json files for all languages may help in order to don't miss a line to translate.

Anyway, thank you all for your work. The adaptation is superb and it's being a pleasure to contribute.

**Comment by kberg** [comment] 2021-03-02 01:13
> I'd like to know if standardization of locales is in the roadmap. We found many inconsistencies such as some strings ending with a dot, whereas others aren't; the same for many words in capital letters, etc.

There's not a specific _roadmap_ by design. It's unfortunate. I spoke with @alrusdi about resolving this but it would not be a trivial change.

> I'll buy Venus Next and Colonies this week and that would be all left.

I won't discourage you from buying copies of the expansions, but you can also read the rules online (the rules PDFs are a non-complicated Google search.)

**Comment by kberg** [comment] 2021-03-02 01:13
I neglected to say: this looks just great.

**Comment by diegombeltran** [comment] 2021-03-02 08:18
> There's not a specific _roadmap_ by design. It's unfortunate. I spoke with @alrusdi about resolving this but it would not be a trivial change.

Something I forgot to say (not entirely related) that could be easier to fix is card titles: When the name of the card is very long (which happens many times in the Spanish version), it exceedes the frame. You can check it in the 4th card, _Asteroide_... I'm no CSS expert but will spend some time so we can fix it.

> I won't discourage you from buying copies of the expansions, but you can also read the rules online (the rules PDFs are a non-complicated Google search.)

True, we have the rules downloaded, but also wanted to translate the cards using the exact and official descriptions, even the name of the corporations which sometimes are translated and sometimes they leave the names untouched. Unless you mean that this is available online too.

> I neglected to say: this looks just great.
Thank you very much :)

**Comment by kberg** [comment] 2021-03-02 16:04
Check out http://terraforming-mars.herokuapp.com/cards

>

**Comment by diegombeltran** [comment] 2021-03-02 17:06
Hello again!

I think you didn't understand me. What I mean is that we are not translating the cards directly, instead we are using the same texts as the cards in the Spanish boxes, to be as rigorous as possible. Other strings like UI, options... are translated by ourselves.

The screenshot in the other comment was the same cards list but deployed on a server.

Thank you anyway!

**Comment by kberg** [comment] 2021-03-02 17:34
:thumbsup:

>

**Comment by diegombeltran** [comment] 2021-03-12 09:02
Hello!

We still have Colonies and Venux Next left. Until we manage to get a copy (which I hope it'll be this week), could we make a PR with the changes?

Thank you!

**Comment by alrusdi** [comment] 2021-03-12 09:04
> We still have Colonies and Venux Next left. Until we manage to get a copy (which I hope it'll be this week), could we make a PR with the changes?

Yes! Any progress is welcome!

**Comment by diegombeltran** [comment] 2021-03-22 07:58
Now it is merged I think we can close this issue! Thank you all

**Comment by alrusdi** [comment] 2021-03-22 08:49
Thanks!

**Closed by alrusdi** 2021-03-22 08:49 UTC
Labels: enhancement
