### ISSUE TITLE
Need newbie-friendly instructions on how to run game locally

### ISSUE THREAD

**Issue by PhantomFFR** [bafolts/terraforming-mars#736] opened 2020-05-29 08:28 UTC
Hello

Thank you all for your work. As someone that barely uses command lines and has no idea about programming, I don't find the "Running" instructions particularly helpful. There appears to be way too much knowledge assumed for someone not well versed in programming/github. Not just to help myself, but hopefully others as well in the future, I'd like a newbie-friendly manual on how to install the game locally. Hopefully, if I describe how I tried to go about installing and running it, where I failed and what my thoughts were, somebody can craft newbie-friendly instructions:

Github to me as just a user has always a bit confusing, so a few days ago, after glancing at the instructions I decided to download a zip of all the code, with the default selection of "Branch: master" selected. After that I looked at the "Running" part a bit more detailed, was confused by what "npm" and "node" means and decided the demo game would suffice for my needs of solo play.

After the obvious pitfalls of the demo ceasing to continue a game when an update is published, I decided to revisit the local installation today. So, first step was to google for "npm", and the first result looked promising, so I installed https://www.npmjs.com/get-npm. [A link to download whatever is needed prior to installing TM would be helpful and erase my doubts whether I actually did follow the instructions correctly or not.] 

Next step, run node.js and type in the (Windows 10) prompt "npm install"... now obviously this does not work as npm wouldn't know what to install, also npm wants to be run in a Windows CMD, so I did that and typed "npm install <directory of the downloaded and unzipped assets>". 

And hey, apparently things are installing. Success? No, not quite, there's a barrage of warnings like "saveError", "notsup", "optional" "deprecated" etc. I'm not quite sure if those should be worrying me or not.

Still, let's try to run it now with "npm run start", which again does nothing. Next idea, since I have no clue whether the installation copied files somewhere else or not I try it with "npm install <directory of the downloaded and unzipped assets>", which again does nothing, not necessarily surprising, but now I'm stuck and decided to seek help, first by looking through the readme again, then clicking links provided by the readme/go to the homepage of bafolts, as he apparently is the initiator and finally posting here.

I have a fear, that even if I got it started at this point, there might be other hindrances that stopped me from actually running TM locally, as the sections about "docker", "docker-compose", "docker-compose + systemd" are completely meaningless to me, so much so that I can't tell if this is just optional settings, or required settings to run TM locally in the first place.

Thanks for reading.

**Comment by bafolts** [comment] 2020-05-29 11:07
This is a good point. It should be easy enough to provide executable builds
with tools like electron. No matter what users will need to know how to
share their wan ip address. With enough new users showing up I might
upgrade the hosting server again as well. Hosting started on a free hobby
heroku plan as I never anticipated this interest.

**Comment by nwai90** [comment] 2020-06-01 16:42
Related to this, would it be a good idea to limit deployments (i.e. merges to master) to consistent fixed daily time windows?

Like a regular "maintenance window" of sorts, so that it can minimise loss of games for active players as everyone will know to avoid games during this time period when changes are being rolled out.

**Comment by vincentneko** [comment] 2020-06-01 16:57
If the database is not recreated when the game is redeployed, the pending games would be reloaded to the last save.
@bafolts did you found how to implement the cache function on heroku you've mentioned ?

**Comment by alrusdi** [comment] 2020-06-01 17:27
We can use another branch for deployments (something like **stable**)

**Comment by vincentneko** [comment] 2020-06-01 18:39
> We can use another branch for deployments (something like **stable**)

Yes or the other way around, link the demo server to a demo branch that could be updated periodically. So master branch will always be up to date.

**Comment by AbnRgr1978** [comment] 2020-06-03 16:03
I would like to echo 110% what PhantomFFR posted and in fact created my own comment prior to searching the existing issues.

Is this TM program suitable for non programmers to try yet?  Much of my free time is spent with the stream version which has become boring and inadequate.  My hard copy solitaire game sits on my game table mocking me for the last 3 months of house arrest.
The instruction at: https://github.com/bafolts/terraforming-mars for running a local server are complex and look inappropriate for a non-programmer.  It appears I could attempt it if I knew what npm and node are; but maybe not.  If someone has time to create a more complete guide I would like to give it a try.
Running it from the demo site has not be satisfactory, numerous unrecoverable server errors.  Our two players games were going well until they were not at which time they were unrecoverable.
.
On the other hand I would not like to distract the code creators from their tasks.  Not knowing how GitHub truly works,  if bandwidth is an issue, I might suggest a collection plate to ease the burden.

**Comment by bafolts** [comment] 2020-06-03 16:57
I can look into revamping the public site. I was never planning on this
project taking off or COVID locking everyone inside. The public site is
going to be easiest for everybody. The cost isn't the issue for me as much
as finding time to do it. As this issue gains users though I gain more
motivation.

**Comment by vincentneko** [comment] 2020-06-03 17:03
In the meantime I've used my son's computer to install the game localy.
His computer is running windows 10. On Mac it should be almost the same.

Here is the walkthrough : [documentation](https://docs.google.com/document/d/1r4GlqA6DkrSAtR6MMYmX_nmh6o4igVTqDUUETiJYGt8/edit?usp=sharing)

If someone can test it and maybe do some screenshots it would be great.

**Comment by AbnRgr1978** [comment] 2020-06-03 17:31
Working on it.

**Comment by AbnRgr1978** [comment] 2020-06-03 21:38
Vincent, I was successful 
[Terraforming Mars GitHub Server install for Dummies Supplement.docx](https://github.com/bafolts/terraforming-mars/files/4726321/Terraforming.Mars.GitHub.Server.install.for.Dummies.Supplement.docx)

waiting for the rest of the story so I can play with my buddy in the next town.

[Mom - the computer cheats.docx](https://github.com/bafolts/terraforming-mars/files/4726326/Mom.-.the.computer.cheats.docx)

Recommend for the totally helpless computer users you identify #of screens to click through, any with a choice that can or needs to be selected and those which take more than a moment to complete.   Also least a sample graphic of the screens of each set.  A couple of times I was concerned something had gone sideways.

I did have one glitch noted in the series highlighted in yellow which was probably caused by interruptions while capturing screen shots.   Was able to successfully recover from that.

Played a solo game immediately after.  Won but lost.  Don’t know why I am annoyed the computer cheated but I hope that can be fixed soon.

**Comment by bafolts** [comment] 2020-06-03 23:38
OK. I think https://github.com/bafolts/terraforming-mars/pull/758 will keep the database around between builds. We will need this to work whether we use `master` or some other branch for the heroku site. I can verify that this keeps the database file around once merged. I am going to look into what database instances heroku provides as it is difficult to manage this on disk dictionary. For the time being it should work fine. I have no idea how many total games are getting played since we lose the database. Once the database file is kept on disk we will get some idea as to how many total games are being played and how much time we have before we will have to prune old games or move to a separate database server.

**Comment by bafolts** [comment] 2020-06-03 23:44
Leveraging electron I still think we should still be able to provide some form of binary which would at least remove the steps of having to install git, node, and npm which is definitely a tall ask for people who are not familiar with these tools. No matter what we do a local user will need to know networking so that they can provide their IP to other users. This was common knowledge back in the day for gaming though and there are probably tutorials online which could be referenced.

**Comment by AbnRgr1978** [comment] 2020-06-04 00:41
If it is just a matter of inserting an IP into "http://localhost:8080/ " address I would be willing to try.  Perhaps/preferably a VPN?  Unfortunately I no longer have a clue how that works any more.  I do have my local server version of TM running successfully and would be very interested in the steps to network it and keep it updated.  My experience is that what was common knowledge back in the day rarely works now.

**Comment by vincentneko** [comment] 2020-06-04 06:40
@AbnRgr1978 
First things first, thanks a lot for your feedback and the extensive documentation. We now have 2 documents to explain how to install the game locally. I will update the readme with this.
About the network setup, it's more complicated than that. I will update my documentation when I have some time.
Last, about your solo game. Did you check the "TR solo mode" option ?
If it's the case, you may have spotted an additional standard project available "Buffer Gas". In order to win with this mode, you have to reach 63 TR before end game. On your screenshot, you are at less.
I will run some tests on my side.

**Comment by AbnRgr1978** [comment] 2020-06-04 14:29
> If it's the case, you may have spotted an additional standard project available "Buffer Gas". In order to win with this mode, you have to reach 63 TR before end game. On your screenshot, you are at less.
Thank you, I vaguely remember that rule but have always ignored that option.  Probably because steam never incorporated it (AFAIR).

**Comment by bafolts** [comment] 2020-06-05 00:35
I will need to do more work for heroku. We create the database file at `../../../db`. I am not sure how we reliably know which directory that will be. Using a remote propped up database is inevitable. Will keep this issue posted.

**Comment by bafolts** [comment] 2020-06-09 01:52
The game is running on heroku and short of any bugs we have with our database storage of game state the games running there should now play fine. I will close this ticket as we added documentation for how to setup locally and the public demo server should be stable enough for long running games.

**Closed by bafolts** 2020-06-09 01:52 UTC
