### ISSUE TITLE
Game died with "Unexpected server response"

### ISSUE THREAD

**Issue by insectman** [bafolts/terraforming-mars#659] opened 2020-05-02 17:51 UTC
https://terraforming-mars.herokuapp.com/player?id=269a0641fc2d

**Comment by bafolts** [comment] 2020-05-02 17:53
@pierrehilbert can we read from the sql database when the server starts up and populate any games that were running? We pushed to master which I am assuming restarted the heroku service and games were lost. We should be able to salvage the games from the database.

**Comment by vincentneko** [comment] 2020-05-02 17:54
I guess it's because of an update of the app.

**Comment by pierrehilbert** [comment] 2020-05-02 18:13
Normally, not having a database file at the beginning shouldn't be a problem, do you have more information about the root cause?

**Comment by vincentneko** [comment] 2020-05-02 20:08
@pierrehilbert the idea here is to be able to load games that were interrupted after a server restart from the database file, so the games can be carried on.

**Comment by bafolts** [comment] 2020-05-03 02:22
Whenever we deploy to master that version goes live on the herokuapp. If
someone was in the middle of the game their game will be lost.

**Comment by vincentneko** [comment] 2020-05-03 09:01
I've pushed on restore_games branch a quick and dirty implementation of loading games from the database at server startup.
I've created a `getAllGames` method in `SQLite` class but due to asynchronous behavior (I guess), I cannot retrieve an array of game id's from this method, hence the hideous sqlite call inside `server`

**Comment by pierrehilbert** [comment] 2020-05-03 11:00
Okay I better understand the problem.
@vincentneko : Yes you will have trouble with the displaying of loaded game but it won't be a problem for those that was playing during the redeployment because they will have to reload the page and that's all.

**Comment by vincentneko** [comment] 2020-05-03 11:40
@pierrehilbert  using the setTimeout trick I was able to get the games id from the SQLite class.
I've also added a status column to games table to be able to distinguish pending games from finished game. The database file must be deleted for the table to be recreated with the additional column.

**Comment by bafolts** [comment] 2020-05-05 01:35
I updated the `README.md` to hope that more people will run the game locally instead of relying on the demo.

**Comment by vincentneko** [comment] 2020-05-06 05:30
The fix is merged. Please check that the database file is not erased when the application redeploy.
I use docker and dockerhub, I had to make a link for the database file with docker :

```
  volumes:
    - "./db:/usr/src/app/db"
```

**Comment by vincentneko** [comment] 2020-05-07 06:51
I'm closing this one, I hope herokuapp is not deleting the database file each time.
Please open a new issue if this happen.

**Closed by vincentneko** 2020-05-07 06:51 UTC
Labels: enhancement
