### ISSUE TITLE
Game struck

### ISSUE THREAD

**Issue by vincentneko** [bafolts/terraforming-mars#41] opened 2019-12-06 11:56 UTC
dabewi and I were having a 2 player game, with prelude extension.
During first generation, both of us were able to play our prelude cards and 2 project cards each.

Then we both have 
"Not your turn to take any actions" message at the bottom of the page.

I'm not sure if it's prelude related or not, will try another 2 player game without prelude when I have some time.

EDIT : I did another 2 player game without prelude, got the same issue during generation 4.

**Comment by alrusdi** [comment] 2019-12-06 15:45
Isn't it fixed by this commit:
https://github.com/bafolts/terraforming-mars/commit/389dcfe3a08bb4fddd5a47d55a2b786e3698f9f9 ?
I've had the same problem, but can't reproduce it after this commit

**Comment by vincentneko** [comment] 2019-12-06 15:56
No I don't think so.
389dcfe fixed a very reproductible bug, I think there is another problem out there.

**Comment by bafolts** [comment] 2019-12-06 16:58
I had a different issue where one player ended up selecting 4 prelude cards instead of 2 initially. I will look into this.

**Comment by bafolts** [comment] 2019-12-06 17:22
OK. I found the situation where the game will get stuck. I don't know why I was able to play through 4 prelude cards once but I will file a separate issue for that as I haven't been able to recreate that issue. In a game with more than 1 player if one player passes and the other continues taking actions the game will eventually get stuck. This is due to an issue in `Game.ts` where only the next player is checked to determine if they have any actions. If that player has no actions to take the game will get stuck. It should move on to the next player.

https://github.com/bafolts/terraforming-mars/blob/master/src/Game.ts#L446

**Comment by bafolts** [comment] 2019-12-06 17:24
This can be recreate by creating a 2 player game and selecting any corporation and project cards. Have one player pass initially. Have the second player take 1 action and continually end their turn. The game will get stuck for the 2nd player after their second round if they went first, or their first if they went second.

**Closed** 2019-12-07 02:08 UTC
Labels: bug
