### ISSUE TITLE
Is Aerospace Mission's test flaky?

### ISSUE THREAD

**Issue by kberg** [bafolts/terraforming-mars#2689] opened 2021-02-06 16:20 UTC
I had a test failure today, 

```
  1) AerospaceMission
       Should play:
     TypeError: Cannot read property 'cb' of undefined
      at Context.<anonymous> (build\tests\cards\community\AerospaceMission.spec.js:1:5009)
```

This came from https://github.com/bafolts/terraforming-mars/actions/runs/543427035 which is now hiding that result. :/

**Comment by bafolts** [comment] 2021-02-13 02:00
It is flaky! Just failed again.

https://github.com/bafolts/terraforming-mars/runs/1891687411?check_suite_focus=true

Was on the windows machine if this gets lost.

**Comment by nwai90** [comment] 2021-02-13 03:32
Will check. Likely something about test setup (e.g. if there are not 2 valid colonies to place on)

**Comment by kberg** [comment] 2021-02-15 15:42
Still flaky: https://github.com/bafolts/terraforming-mars/runs/1904365750?check_suite_focus=true

**Comment by bafolts** [comment] 2021-05-19 00:58
This is duplicate of #3165 . Answer to this question is yes, the aerospace mission's test is flaky.

**Closed by bafolts** 2021-05-19 00:58 UTC
Labels: bug, wontfix
