### ISSUE TITLE
Giant Ice Asteroid bug?

### ISSUE THREAD

**Issue by dabewi** [bafolts/terraforming-mars#247] opened 2020-02-10 18:00 UTC
Hi,

one of my colleagues stumbled over this maybe-bug:

Playing "Giant Ice Asteroid" and then clicking the button to choose a location results in an Input Error. After reloading the page the first ocean tile is placed. After choosing the location for the second ocean tile there is another Input Error (one of that generic errors that sometimes occur) and after reloading the second ocean tile is placed, but the card is still in the hand and playable. You can see it on this screenshot:

https://abload.de/img/4343434ffjqy.png

You can see that 9 ocean tiles are placed and that the card is still in the hand.

Steps to reproduce:

1. Play Giant Ice Asteroid
2. Click on the **lower** "Select Space" button
3. You cannot place both ocean tiles at the same time (if you click on the other button the first one gets deactivated)
4. Click Save
5. -> Error occurs
6. Reload (first ocean tile is placed)
7. Place the second ocean tile
8. -> Error occurs
9. Reload (both ocean tiles are placed)
10. Card is still in handIch habe Giant Ice Asteroid gespielt

**Comment by bafolts** [comment] 2020-02-11 00:49
As another bug was filed today on an older commit was this also on the same version as #248 ?

**Comment by dabewi** [comment] 2020-02-11 09:22
Yes, indeed. I had no time to update my server yet.

**Comment by alrusdi** [comment] 2020-02-13 13:13
@dabewi is it still actual?

**Comment by dabewi** [comment] 2020-02-13 13:26
Hi.

Currently I'm not home and can't restart my server. In the meantime the Giant Ice Asteroid was played without any errors in another game (but on the same server). So I think if it is a bug than it has to do with the order in which you click the "select space" buttons. 

The colleague who encountered the bug clicked on the bottom button first and not on the upper one. The colleague who didn't encounter the bug clicked on the upper button first. 

Also, the Ice Asteroid who also placed two ocean tiles doesn't have two "Select space" buttons visible at the same time but allows to only place the two ocean tiles one after another.

**Comment by alrusdi** [comment] 2020-02-13 13:28
Ok, thak you for clarification. We will try to reproduce and fix this incorrect behavior

**Comment by vincentneko** [comment] 2020-02-13 13:42
Hi,

I can take care of this.

Now we have multiple interrupt mechanism, I plan to move all the SelectSpace (including oceans) that require a player input to be handled when resolving the card to a single point interrupt that will be resolved after the card is played.
This should make cards like GiantIceAsteroid much easier to handle, as well as all temperature increase (because they could trigger a free ocean).

**Comment by bafolts** [comment] 2020-02-14 01:03
Moving everything to the interrupts queue should be fine and make things easier to track and process.

**Comment by vincentneko** [comment] 2020-02-14 12:49
I've pushed some changes in oceans-rework branch.
Can you please test it ?
(for testing purpose, Giant Ice Asteroid is always available in starting hand)

**Comment by vincentneko** [comment] 2020-02-20 06:02
Fixed and merged

**Closed by vincentneko** 2020-02-20 06:02 UTC
Labels: bug
