### ISSUE TITLE
Suggestion: "Observer" players

### ISSUE THREAD

**Issue by ssimeonoff** [bafolts/terraforming-mars#502] opened 2020-03-30 14:33 UTC
Currently you cannot open the other player's areas in another tab/window/screen.

One possible workaround would be to create an "observer id" for every player.
![obs](https://user-images.githubusercontent.com/6917565/77923007-191fbc00-72a2-11ea-81af-f330b8267ce8.png)
When clicked "Observer" link open a new tab:
![obs2](https://user-images.githubusercontent.com/6917565/77923010-19b85280-72a2-11ea-972e-19b0daf60b6c.png)

Div "class="other_player_cont menu" is loaded there - nothing else.

Maybe it is a bad idea, but cannot think of another workaround.

**Comment by glass4pk** [comment] 2020-05-27 10:04
Get the same idea too.

**Comment by kberg** [comment] 2020-10-26 03:29
https://github.com/bafolts/terraforming-mars/issues/1192 may supplant this.

**Comment by chosta** [comment] 2020-12-25 11:27
I am going to work on a spectator mode first thing 2021 and it's going to be a separate UI but the idea is similar to this one.

**Comment by bafolts** [comment] 2021-03-25 18:07
Duplicate of #1192

**Closed by bafolts** 2021-03-25 18:07 UTC
Labels: enhancement, good first issue, wontfix
