### ISSUE TITLE
-6 MC instruction on Hellas south pole is an extra effect, not a cost

### ISSUE THREAD

**Issue by kevinb9n** [bafolts/terraforming-mars#2370] opened 2021-01-14 07:59 UTC
According to the (unofficial) FAQ, I should be able to place my Greenery on the south pole in this situation:

<img width=500 src=https://user-images.githubusercontent.com/934551/104560147-4ef81c00-55fa-11eb-9ac8-78cee9e37152.png>

(not a Turmoil game)

I should then be forced to place the ocean tile next to the existing ocean tile, since it's the only way to get enough cash to satisfy the -6 instruction.

From the FAQ (http://tinyurl.com/terraforming-mars-faq):

![image](https://user-images.githubusercontent.com/934551/104559944-02acdc00-55fa-11eb-88fc-425c42ea6c0c.png)

**Comment by bafolts** [comment] 2021-04-15 14:39
This is duplicate of #3098

**Closed by bafolts** 2021-04-15 14:39 UTC
Labels: bug, wontfix
