### ISSUE TITLE
Some cards start with resources on them randomly

### ISSUE THREAD

**Issue by ssimeonoff** [bafolts/terraforming-mars#461] opened 2020-03-25 09:00 UTC
Forced Precipation has 1 floater even before played.
![90721949_905081343295362_6905203674092404736_n](https://user-images.githubusercontent.com/6917565/77518778-a320ec80-6e7e-11ea-8776-1d1f248a4bc3.png)

Rotator Impacts force you to REMOVE one assteroid on Gen 1. 
![90776823_232631741127119_7577169548277710848_n](https://user-images.githubusercontent.com/6917565/77518785-a4eab000-6e7e-11ea-901d-16850de84636.png)

The bug was observed with other cards holding floaters and microbes. 

E.g. Played Aeriel Mappers round one. Started with 4 floaters on it.

So far, I have experienced the bug only in Solo.

**Comment by alrusdi** [comment] 2020-03-25 09:12
I believe there are two different bugs.
Obviously wrong logic in RotatorImpacts catAct method, and some kind of multiple games on the same server clash in Forced Precipation

**Comment by alrusdi** [comment] 2020-03-25 11:30
I've fixed RotatorImpacts
Resources on cards is magic for me. I can't reproduce it on the localhost.
@bafolts @vincentneko can it be result of initialisation of cards on module level in Dealer.ts
I mean, can different instances of the Game use the same instances on Card?

**Comment by alrusdi** [comment] 2020-03-25 11:40
Domn... It is reproductible:
1) Add this code in Game constructor to put the same card into hand of player
`      const venusCards = ALL_VENUS_PROJECTS_CARDS.slice()
      first.cardsInHand.push(venusCards[12]);`
2) Start two solo games with Venus extension enabled
3) In first game play and activate Forced Precipitation card to have resources on it
4) In second game just refresh the page and you will see unwanted resources on Forced Precipitation card

**Comment by ssimeonoff** [comment] 2020-03-25 11:51
This is a critical bug: 
Game 1: The player with Aridor played tags and got production as expected.
Game 2: The player with Aridor played Jovian and Space tags, but got nothing, because in another ongoing game (Game1), Aridor already has those tags played. The Science tag gave 1 production as expected, because it is not played in Game1.
![games](https://user-images.githubusercontent.com/6917565/77533370-0a4a9b00-6e97-11ea-82e8-78825f073f4e.png)

**Comment by bafolts** [comment] 2020-03-25 13:40
There was a recent change which moved the logic for tracking resources on a card from the game to the instances of the cards themselves. The dealer is providing different games the same instance of the card now as @alrusdi suggested. The change will need to be reverted or the dealer will have to provide new instances of the cards to players.

**Comment by alrusdi** [comment] 2020-03-25 13:42
Or we can store resources on card in game -> resource_count map. But it is, probably, not the solution. We should implement separate cards instances for each game. Any ideas about implementation?

**Comment by bafolts** [comment] 2020-03-25 13:49
I am going to make a card factory that the dealer will use to create each card. There were most likely other bugs we never noticed any time we were using a private property on a class instance to store data.

**Comment by bafolts** [comment] 2020-03-25 15:01
I put up a pull request to fix this. I have the card factories in place but need to finish up the tedious task of porting the remaining cards to the factory syntax. For the time being if you re-start the game server between each game you can avoid these issues. We have a few cards where we store or used to store data specific to that card. This should fix issues we never noticed with those cards as well. I will finish up the mapping to the card factory syntax by the end of the day unless someone beats me to it. The pattern is in place on the pull request if someone wants to finish the work.

**Comment by alrusdi** [comment] 2020-03-26 06:50
This is fixed now. Thanks to @bafolts for great work on it!

**Closed by alrusdi** 2020-03-26 06:50 UTC
Labels: bug
