### ISSUE TITLE
The project card Standard Technology does not work with the Corporation Helion.

### ISSUE THREAD

**Issue by sidoh56** [bafolts/terraforming-mars#1520] opened 2020-10-06 18:19 UTC
I was playing a game last night where I was the Helion corporation and I played the Standard Technology card early on. It is supposed to give you a 3 MC rebate after paying for any standard project except sell patents. I noticed that, any time I paid for something as Helion, it would ask me if I wanted to spend heat or MC or some combination thereof in order to pay for it. The running of this script seemed to prevent Standard Technology from giving me my 3 MC rebate whenever playing standard projects. I know it was this script that caused the problem, because I tried paying for a standard project when I had no heat remaining. This does not trigger the script that asks if you want to spend heat or MC, since there is no heat to spend. In these instances, Standard Technology DID give me my 3 MC rebate, but did not do so in any instance when I had to choose between spending heat or MC, so the problem definitely lies with that script.

**Comment by Lynesth** [comment] 2020-10-10 16:35
I cannot reproduce this issue.
From my tests, money from Standard Technology is actually added before you're asked how to pay.
If worked with and without heat.

**Comment by Lynesth** [comment] 2020-10-11 03:42
Just to add here that it gives you the ability to spend M€ you don't have, just as stated in #1510.

**Comment by alrusdi** [comment] 2020-10-19 11:11
Let's close it as not reproducible

**Closed by alrusdi** 2020-10-19 11:11 UTC
Labels: bug
