### ISSUE TITLE
[Bug] Generalist breaks when playing with all expansions except corporate era

### ISSUE THREAD

**Issue by Maelstrom1** [bafolts/terraforming-mars#1349] opened 2020-09-21 21:50 UTC
My friends and I decided to try something dumb and play a game with every expansion except corporate era. That caused this to happen:
![chrome_AShMGsuPQl](https://user-images.githubusercontent.com/20371049/93825042-7df51700-fc32-11ea-8eb2-6c009b707db7.jpg)

**Comment by vsrisuknimit** [comment] 2020-09-21 23:32
Reproducible and the milestone can be claimed for real.

![image](https://user-images.githubusercontent.com/14239220/93831620-33c76200-fc41-11ea-9f53-524a08d21da1.png)

Seed  ID: 5eecd7f0b7dd

**Comment by vsrisuknimit** [comment] 2020-09-21 23:34
@Maelstrom1 this is because without corporate era, the game starts you out with +1 production of everything.

No bug.

**Comment by Maelstrom1** [comment] 2020-09-22 00:35
You misunderstand. In the rules, it is specified that you must achieve one greater production than you had at the beginning of the game (before corp reveals etc.). So, the one production in everything does not count towards this milestone. It is counted (ignored?) properly when playing with no expansions at all. Generalist is just improperly counting the non-corporate production towards the milestone.

**Comment by vsrisuknimit** [comment] 2020-09-22 13:47
@Maelstrom1 you are certainly right. Sorry for not double checking.

**Comment by Maelstrom1** [comment] 2020-09-22 13:53
It's fine, I'm just glad I could find it so it could be fixed.

**Comment by nwai90** [comment] 2020-09-23 09:38
Fixed and merged

**Closed by nwai90** 2020-09-23 09:38 UTC
Labels: bug
