### ISSUE TITLE
Show how many possible card actions other players have

### ISSUE THREAD

**Issue by illicitonion** [bafolts/terraforming-mars#2205] opened 2020-12-28 20:31 UTC
Sometimes when trying to time an action, it's useful to be able to estimate how many more rounds of actions another player can keep going before passing.

It would be handy to have a "count of unused card actions", in the player overview pane, to at a glance be able to guestimate this.

I could probably try to put this together, if it would be a welcome change - what do folks think?

**Comment by kevinb9n** [comment] 2020-12-28 23:15
Looks like they're thinking about this already, see #2150!

**Comment by bafolts** [comment] 2020-12-29 00:27
I will close this as duplicate of #2150 to send the conversation there.

**Closed by bafolts** 2020-12-29 00:27 UTC
