### ISSUE TITLE
Align linter and formatter

### ISSUE THREAD

**Issue by kberg** [bafolts/terraforming-mars#1931] opened 2020-11-21 15:58 UTC
I've tried a couple of times to format all the Typescript files so it was generally resolved, and would prevent issues like the one I raised in #1927.

One example, I ran a global reformat using `Start: Format files using Glob"
But for example, a reformatted `Game.ts` doesn't come out well:

```
npx eslint src/Game.ts --ext ts

.../git/terraforming-mars/src/Game.ts
   431:47  error  Unexpected space before function parentheses    space-before-function-paren
   490:80  error  Unexpected space before function parentheses    space-before-function-paren
   579:1   error  Expected indentation of 8 spaces but found 6    indent
   580:1   error  Expected indentation of 10 spaces but found 8   indent
   581:1   error  Expected indentation of 10 spaces but found 8   indent
   582:1   error  Expected indentation of 10 spaces but found 8   indent
...
```

Is my formatter wrong? Are we in fact, fully adopting `gts`? How much of this is just me, because I have the wrong settings? Perhaps excluding `.vscode` from git versioning is a mistake.

**Comment by kberg** [comment] 2020-11-21 15:59
While my goal is to help @chosta get unblocked, I think this just will continue to be an issue until we have a global solution.

**Comment by bafolts** [comment] 2020-11-21 16:06
I don't use vscode. Does vscode apply it's own formatting?

**Comment by kberg** [comment] 2020-11-21 16:14
Huh! What do you use?

**Comment by bafolts** [comment] 2020-11-21 16:35
I use VIM and run the lint or fix command to fix syntax issues. What are others doing?

**Comment by kberg** [comment] 2020-11-21 16:45
I'm personally using vscode.

So, how do you know that you're using the gts formatter and linter?

**Comment by bafolts** [comment] 2020-11-21 16:53
I don't run the gts formatter or linter, only `npm run lint` which uses the linting rules `.eslintrc.js` which is extending the `google` eslint rules. Not running any formatter. I see there is a `.prettierrc.yaml`. I think the underlying project here is some people are using formatting and linting rules which our build process is not. Are some people using the `.prettierrc.yaml` file in some way?

**Comment by bafolts** [comment] 2020-11-21 16:57
We haven't fully adopted `gts`. Last time I attempted to integrate I ran into issues I believe were introduced by the `.prettierrc.yaml` I wasn't aware existed. I can try again.

**Comment by kberg** [comment] 2020-11-21 17:07
So, are you sure that you're running the gts linter? For example, after I
installed gts (using `npx gts init`) I got some interesting new compiler
failures, eg, `Fallthrough case in switch.ts(7029)` which suggests that we
possibly aren't using the GTS linter.

>
It's frustrating that gts doesn't publish its style guide as a set of
readable rules. I'm going to see if I can understand what gts actually
endeavors to accomplish.

**Comment by bafolts** [comment] 2020-11-21 17:17
I am positive I am NOT using `gts` to lint. I figured when eslint took in the google styling rules those lined up. I do think `gts` is running `prettier` which does not run. I think `gts` modifies the `tsconfig` file which could be introducing options we don't have. It seemed to be it is easier to _start_ a project with `gts` versus taking it on after the fact.

**Comment by bafolts** [comment] 2020-11-21 17:42
The `prettier` formatter is encorcing the two spaces and `eslint` seems to have differing rules on how it enforces the spacing. @kberg if you run:

```
npx prettier --write src
```

I believe you would see the same spacing changes which are coming in through some pull requests. Having the `prettier` warnings show up while linting would be ideal. Usually `prettier` is ran through a pre-commit hook. For the time being if a PR were put up with the output of `npx prettier --write src` that should catch all the issues coming in. Will need some way to show the warnings during `npm run lint`.

**Comment by chosta** [comment] 2020-11-21 18:06
As a `VSCode` and `prettier` user I can give the following feedback on the current situation:
* Autoformatter with the current settings in `esprettierrc` works with some exceptions
1. It does not automatically separate function and (), so on save any `function():` becomes `function ():` as I've already mentioned in this thread. It needs a eslint rule to override the behavior as prettier is very opinionated on the matter and does not allow for it
2. Some files (after the big formatting PR from @bafolts ) allow for 4 and 2 space tabs at the same time. This is where I do autoformatting with a setting of 2 space tabs (assuming this is what `gts` wants). The reformatting passes the linter but @kberg finds it hard to review (and I agree).

My suggestion is to stick with the linting rules (and maybe change the one that I mentioned in 1.) and decide whether we want 2 or 4 space tabs and do a reformatter PR and make sure `gts` allows for only one of them. Tab spaces are crucial if we want to have consistency imo.

**Comment by bafolts** [comment] 2020-11-21 22:55
I can do PR with these two suggestions. It may be another larger PR again but should stop the changes showing up during pull requests as unrelated changes across the file. Prettier is opinionated by design it seems and is trying to solve this very problem of back and forth on format. This is an old dog new trick type situation for me.

**Comment by Lynesth** [comment] 2020-11-22 00:30
Last time I checked, running `npx gts fix` with the files I wanted to format fixed my issues.

**Comment by Lynesth** [comment] 2020-11-22 00:47
> Some files (after the big formatting PR from @bafolts ) allow for 4 and 2 space tabs at the same time. This is where I do autoformatting with a setting of 2 space tabs (assuming this is what gts wants). The reformatting passes the linter but @kberg finds it hard to review (and I agree).

It allows any number of spaces when it's the first level or indentation:
```ts
export class MyClass {
                // This is fine
                private something = 'something';
}
```

**Comment by chosta** [comment] 2020-12-25 15:11
@kberg maybe close this one?

**Closed** 2020-12-25 15:31 UTC
