### ISSUE TITLE
Missing and repeated tags in full view

### ISSUE THREAD

**Issue by rogerta** [bafolts/terraforming-mars#2198] opened 2020-12-28 15:20 UTC
I'm experiencing missing and repeated tags while playing from a self hosted server, see attached screenshot.  Notice purple player's tags are repeated and red player's tags are missing.

I'm also seeing incorrect wrapping of player info, also in screenshot.  The blue player appears to the right of the gold player and I can't zoom out or scroll the window to see their full info.

The problems go away when I switch to concise view.

**Server info**
deployed: Sat, 26 Dec 2020 18:05:04 -0700
version: d6a5595a

**Browser info**
The screenshot was taken on an Android phone running chrome 89.0.4348.4.

I also experience the same issues on a chromebook running version 87.0.4280.109.

![Screenshot_20201228-091500](https://user-images.githubusercontent.com/2875588/103224003-2206f200-48f5-11eb-9246-69e7e813f9ce.png)

**Comment by SliceOfBread** [comment] 2020-12-28 15:55
Basically a duplicate of #2196

**Comment by bafolts** [comment] 2020-12-28 16:04
I most likely broke this with #2189 . I switched it to use `v-else` and it seemed to work for me but something must be wrong.

**Comment by bafolts** [comment] 2020-12-28 16:07
I will put a fix out and push this to the demo site ASAP.

**Comment by Lynesth** [comment] 2020-12-28 16:13
@bafolts I know we've had 3 reports of this problem already, but I'm really unable to reproduce it.
Also it's showing the full version of tags twice in a row, not the full + the consice, so I'm not sure your change is to blame.

**Comment by bafolts** [comment] 2020-12-28 16:19
I can reproduce. I think the `v-else` is acting on every element of the `v-for`. This should be fixed with https://github.com/bafolts/terraforming-mars/pull/2201/files

**Closed** 2020-12-28 16:24 UTC
Labels: bug

**Comment by rogerta** [comment] 2021-01-02 18:09
Will give it a try shortly on my server once the current games are done.
