### ISSUE TITLE
Settings reset upon page reload

### ISSUE THREAD

**Issue by ainokna** [bafolts/terraforming-mars#3321] opened 2021-05-26 22:06 UTC
I'm sorry if I'm posting a duplicate report.
Recently I've started getting a problem where game settings don't persist on the page reload.
You can see an example in the attached video. (https://youtu.be/6RKbjBF7nZY)
If I click on the setting icon after the reload, the settings get restored.

Also (not in the video), if I manually hide played the event and building cards on my hand, after another player's turn, the cards reappear and don't stay hidden.

**Comment by kberg** [comment] 2021-05-27 03:37
Which browser are you using? I've heard about some issues with non-standard
browsers.

>

**Comment by ainokna** [comment] 2021-05-27 04:29
I'm using Chrome Version 91.0.4472.77 (Official Build) (x86_64) on Mac Big Sur 11.3.1.

**Comment by kberg** [comment] 2021-05-27 05:25
Huh. Fascinating. I'm about to be unavailable for a weekend. If settings
are important to enough for you prefer to move to another server, that
makes sense. However, if you're willing to debug with me, we can take this
off-list. (DM me on Discord.)

@bafolts, is it possible to add the Mac operating system as a github
testbed?

>

**Comment by ainokna** [comment] 2021-05-27 17:47
@kberg, I'd be happy to debug together! I'll ping you on Discord.

**Comment by bafolts** [comment] 2021-05-29 15:38
If I remember I think the bug is seen in any version of chrome. This is duplicate of https://github.com/bafolts/terraforming-mars/issues/1871. Helpful thread from vue-js https://github.com/vuejs/vue/issues/11165.

To avoid relying on the browser for this we will have to hook some DOM event if we can and populate the values.

**Comment by bafolts** [comment] 2021-06-01 00:47
Disregard my comment from earlier. This bug is different from when the back button is pressed. When the preference is toggled from the preference manager we use javascript to add class names which hide the cards in your hand. This javascript doesn't run when the page load. This will happen in every browser.

https://github.com/bafolts/terraforming-mars/blob/main/src/components/PreferencesDialog.ts#L43

This should be updated to leverage vue-js.

**Comment by vsrisuknimit** [comment] 2021-06-01 11:31
@bafolts this was not a problem before two weeks ago. It was introduced by #3309.

**Comment by bafolts** [comment] 2021-06-01 13:33
At a minimum the call to `syncPreferences` which happened through a `data` attribute would have to be put back in place. Leveraging a `v-if` or `v-show` would be ideal in my mind. It took me 20 minutes or so to read through how we were showing and hiding these properties. I first went to the div where we are showing the cards in hand looking for a `v-if` or `v-show`. Without knowing the `setPreferencesCSS` appended a class name which hid the element it was difficult to know how we were hiding or showing the element.

**Closed** 2021-06-03 14:39 UTC
Labels: bug
