### ISSUE TITLE
Flaky unit test or turmoil bug.

### ISSUE THREAD

**Issue by bafolts** [bafolts/terraforming-mars#658] opened 2020-05-02 17:45 UTC
Run the unit tests enough time locally:

```
  1 failing

  1) Turmoil
       Correctly set dominant party:

      AssertionError: expected { Object (partyLeader, delegates, ...) } to equal { Object (partyLeader, delegates, ...) }
      + expected - actual
```

This is either an issue with the unit test or a turmoil bug.

**Comment by pierrehilbert** [comment] 2020-05-02 18:12
I think that the problem is caused by the global event part, I will fix the test.

**Comment by vincentneko** [comment] 2020-05-04 06:57
Fixed one with mudslides as well.

**Closed** 2020-05-04 16:59 UTC
Labels: bug
